### ISSUE TITLE
Different responses when using paypal.detail

### ISSUE THREAD

**Issue by imetallica** [totaljs/node-paypal-express-checkout#14]
Hello, I'm having a problem. When I try to get the detail of the transaction again, it returns an error:
  `````(json)
  { TIMESTAMP: '2015-12-16T17:47:52Z',
  CORRELATIONID: '636e6329e9849',
  ACK: 'Failure',
  VERSION: '52.0',
  BUILD: '18308778',
  L_ERRORCODE0: '10415',
  L_SHORTMESSAGE0: 'Transaction refused because of an invalid argument. See additional error messages for details.',
  L_LONGMESSAGE0: 'A successful transaction has already been completed for this token.',
  L_SEVERITYCODE0: 'Error' }
  `````

I know that Paypal has return success on first call, but is there a better way to check if the payment was successful? What happens if, on the first call to the detail, paypal sends that the payment is still pending?

**Comment by petersirka** [comment]
Hi @imetallica,
sorry for delay. I have same problem with this, but look here:
<https://github.com/petersirka/node-paypal-express-checkout#how-to-prevent-of-pending-paymentstatus>

I have to look into the PayPal documentation.

**Comment by imetallica** [comment]
@petersirka, thanks for the answer. But that guarantees that I'll always receive payments?

**Comment by petersirka** [comment]
I have updated the module, please download it from NPM and please read documentation in `readme.md`.

**Comment by LucasBadico** [comment]
How Do I get the paypal token for retrieve the details?

**Comment by petersirka** [comment]
Hi @LucasBadico,

```javascript
// req.query.token, req.query.PayerID
// paypal.detail('token', 'PayerID', callback);
```
