### ISSUE TITLE
Account / Client / Secret

### ISSUE THREAD

**Issue by wesbos** [totaljs/node-paypal-express-checkout#17]
The new Paypal developer site now only lists the Account, Client ID and Secret - is this the same thing as username, password and signature?

**Comment by petersirka** [comment]
Hi @wesbos,
yes you're right. I have look into it this week.... Thanks for info.

**Comment by wesbos** [comment]
Thanks so much!

**Comment by petersirka** [comment]
I have updated documentation and the module. More info:
<https://github.com/totaljs/node-paypal-express-checkout#paypal-account>

Thank you!
