### ISSUE TITLE
Payment ACK FAilure

### ISSUE THREAD

**Issue by 123maxmix123** [totaljs/node-paypal-express-checkout#20]
Hi, i've tried already everything and i feel that i'm near to solution, but when i complete the payment, and i check details it says failure.

**The same is with rest-sdk**.

I've changed your code a little bit, for my needs, (removed invoice number, changed custom field, and seems work ok).

But even with original code same problem.
My credentials are 100% correct, and when i done the payment it redirects me correctly to success page, but when i check for details it says FAIL!

Any help please?

**Comment by 123maxmix123** [comment]
**AND HERE IS MY FINAL SOLUTION TO ALL PROBLEMS!!!!!!
WHY? IDK, ASK IT TO PAYPAL, THAT OTHERWISE WONT LET ME PAY**

`Paypal.prototype.pay = function(custom_data, amount, description, currency, requireAddress, callback) {

	// Backward compatibility
	if (typeof(requireAddress) === 'function') {
		callback = requireAddress;
		requireAddress = false;
	}

	var self = this;
	var params = self.params();

	//double params becouse PayPal is NOOOB WEBSITE!!!!

	params.PAYMENTACTION = 'Sale';
	params.PAYMENTREQUEST_0_AMT = prepareNumber(amount);
	params.AMT = prepareNumber(amount);
	params.Amt = prepareNumber(amount);
	params.Currencycode = currency;
	params.RETURNURL = self.returnUrl;
	params.CANCELURL = self.cancelUrl;
	params.DESC = description;
	params.NOSHIPPING = requireAddress ? 0 : 1;
	params.ALLOWNOTE = 1;
	params.CURRENCYCODE = currency;
	params.PAYMENTREQUEST_0_CURRENCYCODE = currency;
	params.METHOD = 'SetExpressCheckout';
	//params.INVNUM = invoiceNumber;
	params.CUSTOM = custom_data;

	self.request(self.url, 'POST', params, function(err, data) {

		if (err) {
			callback(err, null);
			return;
		}

		if (data.ACK === 'Success') {
			callback(null, self.redirect + '?cmd=_express-checkout&useraction=commit&token=' + data.TOKEN);
			return;
		}

		callback(new Error('ACK ' + data.ACK + ': ' + data.L_LONGMESSAGE0), null);
	});

	return self;
};`

NOOOOB PAYPAL SYSTEM!!!!!

FOR NEW PEOPLE TO NODE JS:
DONT FORGET TO USE **BodyParser**!

**Comment by petersirka** [comment]
I have fixed this problem.

**Comment by petersirka** [comment]
Please download latest version from NPM.
